### ISSUE TITLE
Inconsistencias vistas en panel: chequear tardanza en replicación de foto

### ISSUE THREAD

**Issue by aibarbetta** [hydro-monitor/web-api#118]
A veces la foto se intenta crear contra un servidor distinto de donde se creó la medición. En algunos casos, las instancias de Cassandra todavía no hicieron catch up de los registros de mediciones y el POST de foto tira un 404 porque la instancia de Cassandra todavía no sabe que esa medición existe.

Posibles soluciones:
* Retry de creación de foto en el servidor
* Retry de creación de foto en el nodo
* Dejar de chequear que la medición existe al crear la foto
* Volver a enviar medición y foto como un request único (en su momento creo que lo habíamos separado por el diseño con múltiples fotos)

**Comment by aibarbetta** [comment]
También pasa con GETs de configuraciones. Vi en el panel como configuraba un nodo y esa configuración desaparecía y volvía a aparecer

**Comment by aibarbetta** [comment]
**Sería ideal que la web-api se comunique con los Cassandras haciendo un round robin, para asegurar que los retries no caen todos en la misma instancia desactualizada**

**Comment by aibarbetta** [comment]
Esto antes se llamaba `POST de foto a veces falla con 404 por que la medición no está creada` ese problema en particular lo mitigue con retries desde el nodo, pero permanece el problema de consistencia entre instancias de Cassandra. Ocurre que a veces la foto esta en algunas instancias y otras no, lo mismo con la configuración de nodo

**Comment by aibarbetta** [comment]
Probar usando proxy con cache? Como squid

**Comment by abrden** [comment]
Cambiar estrategia de haproxy para que en lugar de hacer round robin, use a una instancia como source of truth y haga el fallback a otra cuando esa no este disponible

**Comment by miporto** [comment]
- Probar cambiando el retry strategy de los clients para que pruebe inicialmente con un nivel de consistencia que arranque en quorum y vaya bajando
- Probar seteando por request el nivel de consistencia requerido
