### ISSUE TITLE
Probar queries con 2/3 nodos de Cassandra caídos

### ISSUE THREAD

**Issue by aibarbetta** [hydro-monitor/web-api#128]

**Comment by miporto** [comment]
- Si se baja Azure 1 (el seed node) UNSAdA deja de funcionar (te podes conectar desde ese Cassandra pero la api no anda, gocql: no available host pool). Por otro lado, Azure 2 sigue funcionando correctamente. Hay que ver si la API normalmente se conecta bien al nodo de UNSAdA. Quizás nunca le esta pudiendo pegar.

- Si bajas todo el cluster sí o sí tenés que arrancar por el seed node o no pueden reconectarse al cluster. No es muy terrible que esto sea así pero quizás poniendo a otro nodo como seed node te da mas flexibilidad al a hora de volver a levantar el cluster desde 0.

**Comment by miporto** [comment]
- Averiguar si un nodo cualquiera puede transformarse en seed node una vez que ya arrancó.
- Ver posibilidad de utilizar más de un seed node (¿pueden ser todos seed nodes?)

**Comment by miporto** [comment]
- Poner dos nodos como seed nodes.
- Probar si las demás apis funcionan cuando están todo caídos menos el nodo de unsada.
- Probar que pasa si no se pueden levantar los seed nodes y necesito recrear el cluster.
- Un nodo que no es seed node puede convertirse en tal una vez que ya existe el cluster. Hay que editar el yaml de configuración de cassandra y reiniciar cada nodo.
