### ISSUE TITLE
Documentar requerimientos de software y de hardware

### ISSUE THREAD

**Issue by miporto** [hydro-monitor/web-api#133]

**Comment by aibarbetta** [comment]
@manuporto completar requisitos de hardware de servidor y requisitos de software de base de datos

**Comment by aibarbetta** [comment]
Utilizar `htop` y `lscpu` para medir requerimientos de hw

**Comment by aibarbetta** [comment]
@manuporto Por que el compilador de Go figura como requisito? No se compila en docker?

**Comment by miporto** [comment]
Se compila por fuera. En el container de Docker únicamente se ejecuta
