### ISSUE TITLE
Decidir qué hacer con la cantidad de fotos por medición

### ISSUE THREAD

**Issue by miporto** [hydro-monitor/web-api#52]
El nodo tarda mucho tiempo en enviar una foto al servidor por lo que vale preguntarse si realmente vale la pena esta funcionalidad y si directamente no conviene que se haga una medicion nueva directamente

**Comment by aibarbetta** [comment]
@manuporto no parece algo que quieran y no está en la lista de requerimientos de la propuesta. Lo que si creo que sería interesante es poder setear en 0 la cantidad de fotos a tomar, la implementación actual el servidor admite esto?

En caso de que quieran múltiples fotos por estado, se necesitaría algún cambio del lado del servidor?

**Comment by miporto** [comment]
Hoy en dia no pido el numero de foto pero uno no esta obligado a agregarla, si se quisiera meter mas fotos por medicion basta por empezar a mandar el parametro correspondiente en el request
