### ISSUE TITLE
Levantar cluster de Cassandra con una instancia por servidor

### ISSUE THREAD

**Issue by miporto** [hydro-monitor/web-api#53]
- [x] Levantar cluster de 3 instancias utilizando docker containers en Antiguos
- [ ] Levantar cluster de 3 instancias utilizando instancia de AWS y Antiguos (va a faltar levantarlo en un servidor más por lo que habría que combinarlo con el uso de un container)

Tener en cuenta que solo dos puertos están expuestos en los servidores de FIUBA/UBA, por lo que la solución tiene que funcionar con esos puertos

**Comment by miporto** [comment]
- Levantar cluster utilizando docker containers en Antiguos
- Levantar cluster utilizando instancia de AWS y Antiguos (va a faltar levantarlo en un servidor más por lo que habría que combinarlo con el uso de un container)

**Comment by aibarbetta** [comment]
- [x] Levantar cluster de 3 instancias utilizando docker containers en Antiguos
- [x] Verificar selects e inserts con una instancia UP y dos DOWN (Funcionan con CONSISTENCY ONE)
- [x] Volver a reestablecer las instancias caidas y verificar que los inserts hechos durante el downtime se propagan

**Comment by aibarbetta** [comment]
* https://stackoverflow.com/questions/29323709/unable-to-start-cassandra-node-already-exists
* Replacing a dead node: http://cassandra.apache.org/doc/latest/operating/topo_changes.html#replacing-a-dead-node

**Comment by aibarbetta** [comment]
- [ ] Usar volumenes de datos en los containers
- [ ] Tirar el container que uso un volumen y probar de levantarlo pasándole el flag `-Dcassandra.replace_address=<ip>"` (que no incluye el first_boot)
- [ ] Escribir instructivos para levantar una instancia que estuvo down y una completamente nueva

**Comment by miporto** [comment]
- Probar levantando con los distintos flags usando volumenes en los containers
- Probar agregando nodos sin un volumen

**Comment by aibarbetta** [comment]
Mail Mariano/Ignacio, preguntar por mas servidores

Plantear también dificultades de automatizar el deployment con pocos puertos expuestos y la necesidad de tuneles ssh.
(Ademas de todavía no haber podido resolver cómo conectar a las instancias por medio de túneles)

**Comment by miporto** [comment]
Mandar mail a señor Lujan para que nos levante un AWS y a Mariano para ver si tiene el otro server de FIUBA.
Ver cómo podríamos conectarnos entre servidores por el tema de los puertos.

**Comment by aibarbetta** [comment]
https://stackoverflow.com/questions/2359159/cassandra-port-usage-how-are-the-ports-used
