### ISSUE TITLE
Bootstrap de cluster de cassandra con volumenes persistentes

### ISSUE THREAD

**Issue by aibarbetta** [hydro-monitor/web-api#59]
* Cómo bootstrapear un cluster de cassandra de 0?
* Cómo revivir un nodo caído con su volumen?
* Cómo revivir un nodo caído sin su volumen?
* Cómo revivir tres nodos caídos con sus volúmenes?

Dejar documentado el proceso en cada uno de estos casos.

**Comment by miporto** [comment]
Automaticese

**Comment by miporto** [comment]
Armar scripts para levantar cluster de Cassandras y para levantar el server
