### ISSUE TITLE
Levantar múltiples instancias de api y db para probar nodo y panel hablando con distintas instancias

### ISSUE THREAD

**Issue by aibarbetta** [hydro-monitor/web-api#64]

**Comment by miporto** [comment]
Vamos a necesitar la instancia de AWS arriba o más puertos disponibles en Antiguos

**Comment by miporto** [comment]
#14

**Comment by miporto** [comment]
Workaround: Podemos probar 3 apis con 1 cassandra y 1 frontend (Que esté utilizando haproxy para hablar con las distintas apis)

**Comment by miporto** [comment]
- Hacer un docker-compose para levantar varios servers con un solo nodo de cassandra
