### ISSUE TITLE
Verificar configuración del nodo antes de guardarla

### ISSUE THREAD

**Issue by miporto** [hydro-monitor/web-api#65]

**Comment by aibarbetta** [comment]
Validar que no se solapen los intervalos de estados

**Comment by manuporto** [comment]
https://cassandra.apache.org/doc/latest/faq/#:~:text=By%20default%2C%20Cassandra%20uses%207000,sh%20(through%20JVM%20options).

**Comment by aibarbetta** [comment]
https://www.geeksforgeeks.org/check-if-any-two-intervals-overlap-among-a-given-set-of-intervals/
https://www.golangprograms.com/go-language/interface.html
