### ISSUE TITLE
Pedir key al crear una nueva medición

### ISSUE THREAD

**Issue by aibarbetta** [hydro-monitor/web-api#76]
**para asegurar que el emisor de la medición sea un nodo y no un atacante**

Cambiar creación del nodo para que ahora genere una key. Guardar la key en la tabla de nodos. Asegurarse de que los gets nunca devuelvan la key

**Comment by miporto** [comment]
Hay que generar un JWE, es decir, un token que viaje encriptado entre cliente y servidor. Para esto hay que generar una key publica/privada. La key privada debería tenerla el server y la pública se distribuye entre los nodos.
